# Generated by Django 3.1.7 on 2021-05-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='is_served',
            field=models.BooleanField(default=False),
        ),
    ]
