# Generated by Django 3.1.7 on 2021-04-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accounttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='zone',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
