# Generated by Django 3.1.7 on 2021-04-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accounttype_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
