# Generated by Django 3.1.7 on 2021-04-21 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0002_archivefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivefile',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_archive_files', to='accounts.user'),
            preserve_default=False,
        ),
    ]
