# Generated by Django 3.1.7 on 2021-04-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_archivefile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivefile',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
