# Generated by Django 3.1.7 on 2021-05-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_auto_20210518_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='status',
        ),
        migrations.AddField(
            model_name='filereciever',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
