# Generated by Django 3.1.7 on 2021-05-19 16:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0008_auto_20210519_1608'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ForwardFileReciever',
            new_name='ForwardFileReceiver',
        ),
    ]
