# Generated by Django 3.1.7 on 2021-05-21 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0009_auto_20210519_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='files')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'old_files',
            },
        ),
    ]
