# Generated by Django 3.1.7 on 2021-05-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_oldfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldfile',
            name='file',
            field=models.FileField(upload_to='oldfiles'),
        ),
    ]
